apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jvmo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jvmo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jvmo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jvmo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jvmo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fxvj-tenant/rhtap-demo-app/hacbs-test-project-jvmo@sha256:abd9afc39b89eddc2fe7e023cac428079965bc08897293e865764d0ae6f1ea87
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
